### User signup endpoint
Post http://localhost:5000/api/userinfo/
Content-Type: application/json

{
    "username": "Albert",
    "email": "rabconnection1380@gmail.com",
    "password": "albert123",
    "role": "123456",
    "level": 1,
    "balance": 1,
    "generatedAddress": "1"
}

### User signin endpoint
Post http://localhost:5000/api/userinfo/signin/
Content-Type: application/json

{
    "username": "Albert",
    "password": "albert123"
}

### Get a user profile endpoint
GET http://localhost:5000/api/userinfo
Authorization: 